#!/bin/bash -
#-----------------------------------------------------#
# buildlic
#
# 
#-----------------------------------------------------#
PROGRAM="buildlic"

# References to $SELF
BINDIR="$(dirname "$(readlink -f $0)")"
SELF="$(readlink -f $0)"

# usage - Show usage message and die with $STATUS
usage() {
   STATUS="${1:-0}"
   echo "Usage: ./$PROGRAM
	[ -  ]

-a | --add <arg>              desc
-r | --remove <arg>           desc
-a | --alias <arg>            desc
-e | --edit <arg>             desc
-d | --default <arg>          desc
-v | --verbose                Be verbose in output.
-h | --help                   Show this help and quit.
"
   exit $STATUS
}


# Die if no arguments received.
[ -z "$BASH_ARGV" ] && printf "Nothing to do\n" > /dev/stderr && usage 1

# Process options.
while [ $# -gt 0 ]
do
   case "$1" in
     -a|--add)
         DO_ADD=true
         shift
         ADD="$1"
      ;;
     -r|--remove)
         DO_REMOVE=true
         shift
         REMOVE="$1"
      ;;
     -a|--alias)
         DO_ALIAS=true
         shift
         ALIAS="$1"
      ;;
     -e|--edit)
         DO_EDIT=true
         shift
         EDIT="$1"
      ;;
     -d|--default)
         DO_DEFAULT=true
         shift
         DEFAULT="$1"
      ;;
     -v|--verbose)
        VERBOSE=true
      ;;
     -h|--help)
        usage 0
      ;;
     --) break;;
     -*)
      printf "Unknown argument received.\n" > /dev/stderr;
      usage 1
     ;;
     *) break;;
   esac
shift
done

# add
[ ! -z $DO_ADD ] && {
   printf '' > /dev/null
}

# remove
[ ! -z $DO_REMOVE ] && {
   printf '' > /dev/null
}

# alias
[ ! -z $DO_ALIAS ] && {
   printf '' > /dev/null
}

# edit
[ ! -z $DO_EDIT ] && {
   printf '' > /dev/null
}

# default
[ ! -z $DO_DEFAULT ] && {
   printf '' > /dev/null
}
